TurboAz/TurboAz/Models/Car.cs
namespace TurboAz.Models
{
    public class Car
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public decimal Price { get; set; }
        public string? Color { get; set; }
        public DateTime Year { get; set; }
        public int ModelId { get; set; }
    }
}

TurboAz/TurboAz/Models/Marka.cs
namespace TurboAz.Models
{
    public class Marka
    {
        public int Id { get; set; }
        public string? Name { get; set; }
    }
}

TurboAz/TurboAz/Models/Model.cs
namespace TurboAz.Models
{
    public class Model
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public int MarkaId { get; set; }
    }
}

TurboAz/TurboAz/Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;
using TurboAz.Models;

namespace TurboAz.Controllers
{
    public class CarController : Controller
    {
        private readonly List<Car> _cars;

        public CarController()
        {
            _cars = new()
            {
                new Car {
                    Id = 1,
                    Name = "Bmw M5",
                    Color = "Blue",
                    Price = 30000,
                    Year = new DateTime(2012, 5, 9, 10, 30, 0),
                    ModelId = 1
                },

                new Car {
                    Id = 2,
                    Name = "Bmw M5",
                    Color = "Red",
                    Price = 35000,
                    Year = new DateTime(2013, 5, 9, 10, 30, 0),
                    ModelId = 1
                },

                new Car {
                    Id = 3,
                    Name = "Bmw M5",
                    Color = "Magenta",
                    Price = 20000,
                    Year = new DateTime(2000, 5, 9, 10, 30, 0),
                    ModelId = 1
                },

                new Car {
                    Id = 4,
                    Name = "Mercedes Gle",
                    Color = "Black",
                    Price = 100000,
                    Year = new DateTime(2020, 5, 9, 10, 30, 0),
                    ModelId = 2
                },

                new Car {
                    Id = 5,
                    Name = "Mercedes Gle",
                    Color = "White",
                    Price = 125000,
                    Year = new DateTime(2021, 5, 9, 10, 30, 0),
                    ModelId = 2
                },

                new Car {
                    Id = 6,
                    Name = "Mercedes Gle",
                    Color = "Yellow",
                    Price = 73000,
                    Year = new DateTime(2019, 5, 9, 10, 30, 0),
                    ModelId = 2
                },

                new Car {
                    Id = 7,
                    Name = "Volvo XC40",
                    Color = "Green",
                    Price = 50000,
                    Year = new DateTime(2022, 5, 9, 10, 30, 0),
                    ModelId = 3
                },

                new Car {
                    Id = 8,
                    Name = "Volvo XC40",
                    Color = "Gray",
                    Price = 64000,
                    Year = new DateTime(2020, 5, 9, 10, 30, 0),
                    ModelId = 3
                },

                new Car {
                    Id = 9,
                    Name = "Volvo XC40",
                    Color = "Black",
                    Price = 42000,
                    Year = new DateTime(2021, 5, 9, 10, 30, 0),
                    ModelId = 3
                }
            };
        }

        public IActionResult Index(int? id)
        {
            if (id != null)
            {
                if (!_cars.Exists(m => m.Id == id))
                {
                    return BadRequest();
                }

                return View(_cars.FindAll(m => m.ModelId == id));
            }

            return View(_cars);
        }

        public IActionResult Detail(int? id)
        {
            if (id != null)
            {
                if (!_cars.Exists(m => m.Id == id))
                {
                    return BadRequest();
                }

                return View(_cars.Find(m => m.Id == id));
            }

            return View(_cars);
        }
    }
}

TurboAz/TurboAz/Controllers/MarkaController.cs
using Microsoft.AspNetCore.Mvc;
using TurboAz.Models;

namespace TurboAz.Controllers
{
    public class MarkaController : Controller
    {
        private readonly List<Marka>? _markas;

        public MarkaController()
        {
            _markas = new()
            {
                new Marka {Id = 1, Name = "BMW"},
                new Marka {Id = 2, Name = "Mercedes"},
                new Marka {Id = 3, Name = "Volvo"}
            };
        }

        public IActionResult Index()
        {
            return View(_markas);
        }
    }
}

TurboAz/TurboAz/Controllers/ModelController.cs
using Microsoft.AspNetCore.Mvc;
using TurboAz.Models;

namespace TurboAz.Controllers
{
    public class ModelController : Controller
    {
        private readonly List<Model> _models;

        public ModelController()
        {
            _models = new()
            {
                new Model {Id = 1, Name = "M5", MarkaId = 1},
                new Model {Id = 2, Name = "Gle", MarkaId = 2},
                new Model {Id = 3, Name = "XC40", MarkaId = 3},
            };
        }

        public IActionResult Index(int? id)
        {
            if (id != null)
            {
                if (!_models.Exists(m => m.Id == id))
                {
                    return BadRequest();
                }

                return View(_models.FindAll(m => m.MarkaId == id));
            }

            return View(_models);
        }
    }
}

TurboAz/TurboAz/Views/Car/Detail.cshtml
@model Car

@{
    ViewData["Title"] = "Detail";
}

<h1>Car Detail</h1>

<div class="list-group">
    <ul class="list-group">
        <a class="list-group-item list-group-item-action">
            @Model.Name,
            @Model.Price,
            @Model.Color,
            @Model.Year.ToString("yyyy")
        </a>
    </ul>
    <a asp-controller="Car" asp-action="Index" asp-route-id="@Model.ModelId" class="list-group-item list-group-item-action text-danger">Back</a>
</div>

TurboAz/TurboAz/Views/Car/Index.cshtml
@model List<Car>

@{
    ViewData["Title"] = "Index";
}

<h2>Cars</h2>

<div class="list-group">
    <ul class="list-group">
        @foreach (var car in Model)
        {
            <a asp-controller="Car" asp-action="Detail" asp-route-id="@car.Id" class="list-group-item list-group-item-action">
                @car.Name,
                @car.Price
            </a>
        }
    </ul>
    <a asp-controller="Model" asp-action="Index" asp-route-id="@Model.FirstOrDefault()?.ModelId" class="list-group-item list-group-item-action text-danger">Back</a>
</div>

TurboAz/TurboAz/Views/Marka/Index.cshtml
@model List<Marka>

@{
    ViewData["Title"] = "Index";
}

<h2>Markas</h2>

<div class="list-group">
    <ul class="list-group">
        @foreach (var marka in Model)
        {
            <a asp-controller="Model" asp-action="Index" asp-route-id="@marka.Id" class="list-group-item list-group-item-action">@marka.Name</a>
        }
    </ul>
</div>

TurboAz/TurboAz/Views/Model/Index.cshtml
@model List<Model>

@{
    ViewData["Title"] = "Index";
}

<h2>Models</h2>

<div class="list-group">
    <ul class="list-group">
        @foreach (var modell in Model)
        {
            <a asp-controller="Car" asp-action="Index" asp-route-id="@modell.Id" class="list-group-item list-group-item-action">@modell.Name</a>
        }
    </ul>
    <a asp-controller="Marka" asp-action="Index" class="list-group-item list-group-item-action text-danger">Back</a>
</div>

TurboAz/TurboAz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>